name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.63.2'
      - run: npm ci
      - run: npm ci --prefix ./functions
      - run: npm run deploy:production
